apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jsob
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jsob
    app.kubernetes.io/part-of: byoc-app-tptd
  name: jsob
spec:
  rules:
  - host: jsob-byoc-ihvg-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-8k7bg.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: jsob
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
